groups: []
resources:
- name: git
  type: git
  source:
    private_key: ((halfpipe-github.private_key))
    uri: git@github.com:springernature/halfpipe-deploy-resource.git
    branch: refactor
  check_every: 10m
- name: docker-registry-image-dev
  type: docker-image
  source:
    repository: eu.gcr.io/halfpipe-io/cf-resource-refactor
    tag: dev
    password: ((halfpipe-gcr.private_key))
    username: _json_key
- name: docker-registry-image-stable
  type: docker-image
  source:
    repository: eu.gcr.io/halfpipe-io/cf-resource-refactor
    tag: stable
    password: ((halfpipe-gcr.private_key))
    username: _json_key
- name: cf
  type: cf-resource
  source:
    api: ((cloudfoundry.api-snpaas))
    org: engineering-enablement
    password: ((cloudfoundry.password))
    space: integration_test
    username: ((cloudfoundry.username))
  check_every: 24h
resource_types:
- name: cf-resource
  type: registry-image
  source:
    repository: eu.gcr.io/halfpipe-io/cf-resource-refactor
    tag: dev
    password: ((halfpipe-gcr.private_key))
    username: _json_key

jobs:
- name: Create test docker image
  serial: true
  plan:
  - get: git
    trigger: true
  - put: docker-registry-image-dev
    params:
      tag_file: git/.docker-dev-tag
      build: git

- name: Test resource cf6
  serial: true
  plan:
  - get: git
    passed:
    - Create test docker image
  - get: docker-registry-image-dev
    passed:
    - Create test docker image
    trigger: true
  - put: cf
    params:
      appPath: git/.integration_test
      command: halfpipe-push
      gitRefPath: git/.git/ref
      manifestPath: git/.integration_test/manifest-cf6.yml
      testDomain: springernature.app
  - put: cf
    params:
      command: halfpipe-check
      manifestPath: git/.integration_test/manifest-cf6.yml
  - put: cf
    params:
      command: halfpipe-promote
      manifestPath: git/.integration_test/manifest-cf6.yml
      testDomain: springernature.app
  ensure:
    put: cf
    params:
      command: halfpipe-cleanup
      manifestPath: git/.integration_test/manifest-cf6.yml

- name: Test resource cf7
  serial: true
  plan:
    - get: git
      passed:
        - Create test docker image
    - get: docker-registry-image-dev
      passed:
        - Create test docker image
      trigger: true
    - put: cf
      params:
        appPath: git/.integration_test
        command: halfpipe-push
        gitRefPath: git/.git/ref
        manifestPath: git/.integration_test/manifest-cf7.yml
        testDomain: springernature.app
    - put: cf
      params:
        command: halfpipe-check
        manifestPath: git/.integration_test/manifest-cf7.yml
    - put: cf
      params:
        command: halfpipe-promote
        manifestPath: git/.integration_test/manifest-cf7.yml
        testDomain: springernature.app
  ensure:
    put: cf
    params:
      command: halfpipe-cleanup
      manifestPath: git/.integration_test/manifest-cf7.yml

- name: Create stable docker image
  serial: true
  plan:
  - get: git
    passed:
    - Test resource cf6
    - Test resource cf7
    trigger: true
  - put: docker-registry-image-stable
    params:
      build: git
      tag_file: git/.docker-stable-tag
