resources:
- name: git
  type: git
  source:
    private_key: ((github.private_key))
    uri: git@github.com:springernature/halfpipe-deploy-resource.git

- name: cf-plugin-release
  type: github-release
  source:
    owner: springernature
    repository: halfpipe-cf-plugin

- name: docker-registry-image-dev
  type: docker-image
  source:
    password: ((docker-hub-pe.password))
    repository: platformengineering/cf-resource-tmp
    username: platformengineering
    tag: dev


jobs:
- name: Create test docker image
  serial: true
  plan:
  - get: git
    trigger: true
  - get: cf-plugin-release
    trigger: true
  - put: docker-registry-image-dev
    params:
      dockerfile: git/Dockerfile
      tag_file: git/.docker-dev-tag
      additional_tags: cf-plugin-release/tag