# fly -t engineering-enablement set-pipeline -p halfpipe-deploy-resource-v2 -c .pipeline.yml

groups: []
resources:
- name: git
  type: git
  source:
    private_key: ((halfpipe-github.private_key))
    uri: git@github.com:springernature/halfpipe-deploy-resource.git
  check_every: 10m
- name: docker-registry-image-dev
  type: docker-image
  source:
    repository: eu.gcr.io/halfpipe-io/cf-resource-v2-dev
    password: ((halfpipe-gcr.private_key))
    username: _json_key
- name: docker-registry-image-stable
  type: docker-image
  source:
    repository: eu.gcr.io/halfpipe-io/cf-resource-v2
    tag: stable
    password: ((halfpipe-gcr.private_key))
    username: _json_key
- name: docker-registry-image-stable-dockerhub
  type: docker-image
  source:
    repository: platformengineering/cf-resource-v2
    username: ((platformengineering-dockerhub.username))
    password: ((platformengineering-dockerhub.password))
- name: cf
  type: cf-resource
  source:
    api: ((cloudfoundry.api-snpaas))
    org: engineering-enablement
    password: ((cloudfoundry.password-snpaas))
    space: integration_test
    username: ((cloudfoundry.username-snpaas))
  check_every: 24h
resource_types:
- name: cf-resource
  type: registry-image
  source:
    repository: eu.gcr.io/halfpipe-io/cf-resource-v2-dev
    password: ((halfpipe-gcr.private_key))
    username: _json_key

jobs:
- name: Push test resource
  serial: true
  plan:
  - get: git
    trigger: true
  - put: docker-registry-image-dev
    params:
      build: git

- name: Test resource cf6
  serial: true
  plan:
  - get: git
    passed:
    - Push test resource
  - get: docker-registry-image-dev
    passed:
    - Push test resource
    trigger: true
  - put: cf
    params:
      appPath: git/.integration_test
      command: halfpipe-push
      gitRefPath: git/.git/ref
      manifestPath: git/.integration_test/manifest-cf6.yml
      testDomain: springernature.app
  - put: cf
    params:
      command: halfpipe-check
      manifestPath: git/.integration_test/manifest-cf6.yml
  - put: cf
    params:
      command: halfpipe-promote
      manifestPath: git/.integration_test/manifest-cf6.yml
      testDomain: springernature.app
  ensure:
    put: cf
    params:
      command: halfpipe-cleanup
      manifestPath: git/.integration_test/manifest-cf6.yml

- name: Test resource cf7
  serial: true
  plan:
    - get: git
      passed:
        - Push test resource
    - get: docker-registry-image-dev
      passed:
        - Push test resource
      trigger: true
    - put: cf
      params:
        appPath: git/.integration_test
        command: halfpipe-push
        gitRefPath: git/.git/ref
        manifestPath: git/.integration_test/manifest-cf7.yml
        testDomain: springernature.app
        cliVersion: cf7
    - put: cf
      params:
        command: halfpipe-check
        manifestPath: git/.integration_test/manifest-cf7.yml
        cliVersion: cf7
    - put: cf
      params:
        command: halfpipe-promote
        manifestPath: git/.integration_test/manifest-cf7.yml
        testDomain: springernature.app
        cliVersion: cf7
  ensure:
    put: cf
    params:
      command: halfpipe-cleanup
      cliVersion: cf7
      manifestPath: git/.integration_test/manifest-cf7.yml

- name: Push resource
  serial: true
  plan:
  - get: git
    passed:
    - Test resource cf6
    - Test resource cf7
    trigger: true
  - put: docker-registry-image-stable
    params:
      build: git
      tag_file: git/.docker-stable-tag
      tag_as_latest: true
  - put: docker-registry-image-stable-dockerhub
    params:
      build: git
      tag_file: git/.docker-stable-tag
      tag_as_latest: true
