resources:
- name: git
  type: git
  source:
    private_key: ((github.private_key))
    uri: git@github.com:springernature/halfpipe-deploy-resource.git

- name: cf-plugin-release
  type: github-release
  source:
    owner: springernature
    repository: halfpipe-cf-plugin

- name: docker-registry-image-dev
  type: docker-image
  source:
    password: ((docker-hub-pe.password))
    repository: platformengineering/cf-resource-tmp
    username: platformengineering
    tag: dev


jobs:
- name: Create test docker image
  serial: true
  plan:
  - get: git
    trigger: true
  - get: cf-plugin-release
    trigger: true
  - task: Create temp folder with both resource src and plugin from release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: alpine
      run:
        path: /bin/sh
        args:
        - -ec
        - |
          cp -r git build
          cp cf-plugin-release/cf-plugin-release build/cf-plugin-release
        dir: git
      inputs:
      - name: git
      - name: cf-plugin-release
      outputs:
      - name: build
  - put: docker-registry-image-dev
    params:
      build: build
      tag_file: git/.docker-dev-tag
      additional_tags: cf-plugin-release/tag